# Автоматично завершувати сесію, коли закривається останнє вікно/панель
set -g destroy-unattached on

# Або, щоб tmux завершував роботу відразу після виходу з оболонки (exit)
set -g exit-empty on

# Додайте ці рядки на початок файлу ~/.tmux.conf
set -g extended-keys on
set -as terminal-features 'xterm*:extkeys'

# Також корисно зменшити час очікування після натискання ESC
set -s escape-time 0

# Автоматичне розбиття на 4 панелі (2x2) при створенні нової сесії та запуск програм
set-hook -g after-new-session ' \
    split-window -h; \
    split-window -v; \
    split-window -v -t 0; \
    select-layout tiled; \
    send-keys -t 0 "mc" C-m; \
    send-keys -t 1 "htop" C-m; \
    select-pane -t 0'


# Перехід між панелями через Alt + h,j,k,l
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D
bind -n M-s set-window-option synchronize-panes

bind -n M-р select-pane -L
bind -n M-д select-pane -R
bind -n M-л select-pane -U
bind -n M-о select-pane -D
bind -n M-і set-window-option synchronize-panes

# Максимізація панелі (Zoom) через Alt + w
bind -n M-o resize-pane -Z
bind -n M-ц resize-pane -Z

# Увімкнення миші (щоб можна було змінювати розмір панелей)
set -g mouse on

# Вимикаємо статус-бар (якщо ще не додали)
set -g status off

# Колір межі активної панелі (наприклад, яскраво-зелений)
set -g pane-active-border-style fg=yellow,bg=default

# Колір меж неактивних панелей (тьмяний сірий)
set -g pane-border-style fg=colour238

# Додатково: відображати назву/індикатор активної панелі прямо в її межі
# set -g pane-border-status top
# set -g pane-border-format " [ #P: #{pane_current_command} ] "

