vim.opt.runtimepath:append("~/.config/nvim/keymap")

vim.api.nvim_set_keymap('i', '<M-u>', '<Esc>:set keymap=ukrainian-custom<CR>li', { noremap = true, silent = true })
vim.api.nvim_set_keymap('i', '<M-r>', '<Esc>:set keymap=russian-custom<CR>li', { noremap = true, silent = true })
vim.api.nvim_set_keymap('i', '<M-e>', '<Esc>:set keymap=<CR>li', { noremap = true, silent = true })
vim.api.nvim_set_keymap('v', '<M-u>', '<Esc>:set keymap=ukrainian-custom<CR>gv', { noremap = true, silent = true })
vim.api.nvim_set_keymap('v', '<M-r>', '<Esc>:set keymap=russian-custom<CR>gv', { noremap = true, silent = true })
vim.api.nvim_set_keymap('v', '<M-e>', '<Esc>:set keymap=<CR>gv', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<M-u>', ':set keymap=ukrainian-custom<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<M-r>', ':set keymap=russian-custom<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<M-e>', ':set keymap=<CR>', { noremap = true, silent = true })
