-- Basic config
require("core.mappings")
require("core.plugins")
require("core.colors")
require("core.configs")
require("core.language_mode")
-- Plugins config
require("plugins.telescope") -- Пошукова система файлів, буферів та ін.
require("plugins.lsp")
require("plugins.mason")
require("plugins.cmp")
-- require("plugins.nullls")
require("plugins.lualine")
require("plugins.gitsigns")
-- require("plugins.treesitter")
require("plugins.toggleterm")
-- require("plugins.outline")
require("plugins.autopairs")
require("plugins.comments")
require("plugins.autotag")
require("plugins.buffline")
require("plugins.neotree")
require("plugins.dashboard")
-- require("plugins.nvimsurround")
-- require("plugins.whichkey")
require("plugins.vimtex")
require("plugins.icons")
require("plugins.emmet")

